Traceback (most recent call last):
  File "/Users/kevinge/anaconda3/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/kevinge/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kevinge/anaconda3/lib/python3.11/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kevinge/anaconda3/lib/python3.11/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kevinge/anaconda3/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/kevinge/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/kevinge/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/kevinge/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import os

#Verify environment variables are correct

NB_UID = int(os.environ['NB_UID'])
NB_GID = int(os.environ['NB_GID'])
NB_GROUP = os.environ['NB_GROUP']

XDG_CACHE_HOME = f"/home/{NB_USER}/.cache/"

UID_LOWER_BOUND = 2000  
UID_UPPER_BOUND = 60000 

GID_LOWER_BOUND = 2000  
GID_UPPER_BOUND = 60000 

EXPECTED_NB_GROUP = 'root'

err = []

def check_environment_test():
    if not (UID_LOWER_BOUND <= NB_UID <= UID_UPPER_BOUND):
         err.append(f"NB_UID {NB_UID} is not within the acceptable range: {UID_LOWER_BOUND}-{UID_UPPER_BOUND}.")


    if not (GID_LOWER_BOUND <= NB_GID <= GID_UPPER_BOUND):
         err.append(f"NB_GID {NB_GID} is not within the acceptable range: {GID_LOWER_BOUND}-{GID_UPPER_BOUND}.")


    if  NB_GROUP != EXPECTED_NB_GROUP:
         err.append("NB_GROUP does not match " + "'" + EXPECTED_NB_GROUP + "'")


    if NB_USER != 'jovyan':
         err.append("NB_USER does not match 'jovyan'.")


    if XDG_CACHE_HOME != '/home/jovyan/.cache/':
         err.append("XDD_CACHE_HOME does not match expected path: /home/jovyan/.cache/")


    if len(err) != 0:
         err.append("Environmental Variables test")

    else:
        s = '; '.join(err)
        print("Environmental Variables test ERROR: " + s)
    
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mKeyError[0m                                  Traceback (most recent call last)
Cell [0;32mIn[3], line 5[0m
[1;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01mos[39;00m
[1;32m      3[0m [38;5;66;03m#Verify environment variables are correct[39;00m
[0;32m----> 5[0m NB_UID [38;5;241m=[39m [38;5;28mint[39m(os[38;5;241m.[39menviron[[38;5;124m'[39m[38;5;124mNB_UID[39m[38;5;124m'[39m])
[1;32m      6[0m NB_GID [38;5;241m=[39m [38;5;28mint[39m(os[38;5;241m.[39menviron[[38;5;124m'[39m[38;5;124mNB_GID[39m[38;5;124m'[39m])
[1;32m      7[0m NB_GROUP [38;5;241m=[39m os[38;5;241m.[39menviron[[38;5;124m'[39m[38;5;124mNB_GROUP[39m[38;5;124m'[39m]

File [0;32m<frozen os>:679[0m, in [0;36m__getitem__[0;34m(self, key)[0m

[0;31mKeyError[0m: 'NB_UID'
KeyError: 'NB_UID'

